export const watchProducts = [
  {
    id: "ww1",
    badge: "New",
    img: "https://www.apple.com/v/os/e/images/watchos/liquid_glass/navigation__gdkvxthggeai_large_2x.jpg",
    category: "Watch",
    name: "Apple Watch Series 11",
    desc: "Thinnest Apple Watch ever. Bigger display, advanced health sensors, and watchOS 11.",
    price: "₹46,900",
    sub: "42mm · GPS + Cellular",
  },

  {
    id: "ww2",
    badge: "",
    img: "https://www.apple.com/v/apple-watch-se-3/b/images/overview/health/health_vitals__dor254sdht26_large_2x.jpg",
    category: "Watch",
    name: "Apple Watch SE",
    desc: "The perfect entry into Apple Watch. Crash Detection, heart rate monitoring, and more.",
    price: "₹24,900",
    sub: "40mm · GPS",
  },
];

export const bandProducts = [
  {
    id: "wb1", 
    badge: "New",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MJ5C4_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
     name: "46mm Pride Edition Sport Loop",
    desc: "Soft woven nylon with a breathable design and hook-and-loop fastening for all-day comfort.",
    price: "₹3,900", 
    sub: "Celebrating Pride • 42mm / 46mm",
  },
  {
    id: "wb2", 
    badge: "Popular",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGJ44ref_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
    name: "46mm Gold Milanese Loop - M/L",
    desc: "Elegant stainless steel mesh with a magnetic clasp for a refined and secure fit.",
    price: "₹9,100", 
    sub: "Premium Stainless Steel • M/L",
  },
  {
    id: "wb3", 
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGD64_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
    name: "46mm Blue Ribbon Nike Sport Loop",
    desc: "Lightweight Nike-designed woven band with reflective threads and exceptional breathability.",
    price: "₹4,200", 
    sub: "Nike Edition • Sport Ready",
  },
  {
    id: "wb4", 
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MFM64ref_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
    name: "46mm Green Gray Braided Solo Loop - Size 0",
    desc: "Stretchable recycled yarn construction with a seamless braided design and precise fit.",
    price: "₹8,800", 
    sub: "Braided Design • Size 0",
  },
  {
    id: "wb5", 
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MYPD3ref_AV1_GEO_US?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
    name: "49mm Black Ocean Band - Black Titanium Finish",
    desc: "High-performance elastomer band engineered for water sports and extreme adventures.",
    price: "₹9,100", 
    sub: "Black Titanium • Ultra Compatible",
  },
  {
    id: "wb6", 
    badge: "Special",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MYGU3ref_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Band",
    name: "42mm Black Unity Sport Band - Unity Bloom - S/M",
    desc: "Durable fluoroelastomer with a unique Unity Bloom design and comfortable everyday fit.",
    price: "₹4,500", 
    sub: "Unity Bloom Edition • S/M",
  },
];

export const chargerProducts = [
  {
    id: "wc1", 
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MT0H3?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Charger",
    name: "Magnetic Fast Charger to USB-C Cable (1m)",
    desc: "Magnetic charging cable with fast-charge support for compatible Apple Watch models.",
    price: "₹2,900", 
    sub: "1m Length • USB-C",
  },
  {
    id: "wc2", 
    badge: "Best Seller",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HSB72?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Charger",
    name: "Zens USB-C to USB-C Charging Cable Pro 3 - Dark Cherry",
    desc: "Premium braided USB-C cable designed for fast charging, durability, and everyday use.",
    price: "₹8,999", 
    sub: "Dark Cherry • Pro 3",
  },
  {
    id: "wc3", 
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HRXY2_AV1?wid=532&hei=582&fmt=png-alpha",
    category: "Charger",
    name: "Scosche WatchIt Keychain Apple Watch Magnetic Fast Charger - White",
    desc: "Compact keychain charger with built-in magnetic charging for Watch on the go.",
    price: "₹2,900", 
    sub: "Portable Design • Watch",
  },
];