export const caseProducts = [
  {
    id: "ip1", 
    badge: "New",
    name: "iPhone 17 Pro TechWoven Case with MagSafe – Blue",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGF44?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Case", 
    desc: "Premium woven finish with built-in MagSafe magnets for effortless attachment.",
    price: "₹5,100", 
    sub: "MagSafe compatible",
  },
  {
    id: "ip2", 
    badge: "Best Seller",
    name: "iPhone 17e Silicone Case with MagSafe – Light Moss",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MHWF4?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Case", 
    desc: "Soft-touch silicone exterior with microfiber lining for everyday protection.",
    price: "₹4,300", 
    sub: "MagSafe compatible",
  },
  {
    id: "ip3", 
    badge: "",
    name: "Tech21 FlexQuartz Case for iPhone Air (MagSafe compatible)",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HSGB2?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Case", 
    desc: "Crystal-clear design with advanced impact protection and MagSafe support.",
    price: "₹4,900", 
    sub: "Drop protection up to 2m",
  },
];

export const chargerProducts = [
  {
    id: "ip4", 
    badge: "Popular",
    name: "Apple 20W USB‑C Power Adapter",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MWVV3?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Charger", 
    desc: "Compact fast charger for iPhone, iPad, and AirPods.",
    price: "₹1,900", 
    sub: "20W USB-C output",
  },
  {
    id: "ip5", 
    badge: "New",
    name: "Apple 35W Dual USB‑C Adapter",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MW2H3?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Charger", 
    desc: "Charge two devices simultaneously with intelligent power distribution.",
    price: "₹3,500", 
    sub: "Dual USB-C ports",
  },
  {
    id: "ip6", 
    badge: "",
    name: "Anker 65W GaN USB-C Charger",
    img: "https://cdn.shopify.com/s/files/1/0493/9834/9974/products/A2663111-Anker_715_Charger_Nano_II_65W_1600x.png",
    category: "Charger", 
    desc: "Powerful GaN technology delivers fast charging in a compact design.",
    price: "₹2,499", 
    sub: "65W fast charging",
  },
];

export const cableProducts = [
  {
    id: "ip7", 
    badge: "New",
    name: "USB-C to Lightning Cable (1m)",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MM0A3?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Cable", 
    desc: "Fast charging and reliable data syncing for iPhone, iPad, and AirPods.",
    price: "₹1,700", 
    sub: "1 metre length",
  },
  {
    id: "ip8", 
    badge: "",
    name: "USB-C to Lightning Cable (2m)",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MQGH2?wid=890&hei=890&fmt=jpeg&qlt=90",
    category: "Cable", 
    desc: "Extra-long cable for convenient charging and syncing from a distance.",
    price: "₹2,500", 
    sub: "2 metre length",
  },
  {
    id: "ip9", 
    badge: "Popular",
    name: "240W USB-C Charge Cable (2m)",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MU2G3?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Cable", 
    desc: "Supports ultra-fast 240W charging and high-speed data transfer.",
    price: "₹2,599", 
    sub: "240W Power Delivery",
  },
];

export const magSafeProducts = [
  {
    id: "ip10", 
    badge: "Best Seller",
    name: "MagSafe Charger (1m)",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGD74?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "MagSafe", 
    desc: "Wireless magnetic charging that snaps perfectly onto compatible iPhones.",
    price: "₹3,700", 
    sub: "Up to 25W charging",
  },
  {
    id: "ip11", 
    badge: "New",
    name: "MagSafe Duo Charger",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MHXF3",
    category: "MagSafe", 
    desc: "Foldable charger designed for both iPhone and Apple Watch.",
    price: "₹11,900", 
    sub: "Travel-friendly design",
  },
  {
    id: "ip12", 
    badge: "",
    name: "Belkin BoostCharge Pro 2-in-1",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HRX12?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "MagSafe", 
    desc: "Premium magnetic charging stand for iPhone and AirPods.",
    price: "₹11,299", 
    sub: "2-in-1 wireless charging",
  },
];

export const screenProducts = [
  {
    id: "ip13", 
    badge: "Popular",
    name: "Belkin UltraGlass 2 for iPhone 17 Pro",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HS832?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Screen Protector", 
    desc: "Premium tempered glass protection with exceptional scratch resistance.",
    price: "₹3,499", 
    sub: "UltraGlass 2 technology",
  },
  {
    id: "ip14", 
    badge: "",
    name: "Belkin UltraGlass 2 Privacy for iPhone Air",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HSE62?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Screen Protector", 
    desc: "Keeps your screen visible only to you while protecting against scratches.",
    price: "₹4,199", 
    sub: "Privacy protection",
  },
];

export const powerBankProducts = [
  {
    id: "ip15", 
    badge: "Popular",
    name: "iPhone Air MagSafe Battery",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGPG4?wid=890&hei=890&fmt=jpeg&qlt=90",
    category: "Power Bank", 
    desc: "Magnetic battery pack that attaches securely for wireless charging on the go.",
    price: "₹9,200", 
    sub: "MagSafe compatible",
  },
  {
    id: "ip16", 
    badge: "Best Seller",
    name: "ShiftCam SnapLight Magnetic LED Selfie Ring Light",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HRJ42?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Power Bank", 
    desc: "Portable magnetic LED ring light for brighter selfies and video calls.",
    price: "₹4,999", 
    sub: "Adjustable brightness",
  },
  {
    id: "ip17", 
    badge: "New",
    name: "ShiftCam SnapGrip Pro with Next Generation Powerbank",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HS482?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Power Bank", 
    desc: "Camera-style grip with built-in battery and wireless charging support.",
    price: "₹8,199", 
    sub: "Grip + Power Bank",
  },
];