export const airpodsProducts = [
  {
    id: "a1",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-pro-3-hero-select-202509?wid=532&hei=582&fmt=png-alpha&.v=cmp4MmZ6OWxOeHNNTXh4SzlBNUpEb1RucE9zZTI5eEREaWZpY29lSld3eG5ybFVoUG5ONDlkK2JkbHErdVFSNVM0TjRWdzF2UjRGVEY0c3dBQVZ6VFk1ZmVZeDNxQ3ljaDhwR2JKTTZHaDg",
    category: "AirPods",
    name: "AirPods Pro 3",
    desc: "Redesigned for a better fit. Personalized Spatial Audio and adaptive noise control built in.",
    price: "₹22,900",
    sub: "Active Noise Cancellation",
  },
  {
    id: "a2",
    badge: "New",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-max-select-202409-purple_FV1?wid=976&hei=916&fmt=jpeg&qlt=90&.v=azQxRkVJKzd6V3J0aGNqWFhLMzBmdEFZMGtjOXNTYXJEaHFYa1lFVzIyUnJHdFc3SWNOdWRSclF6WTRFc2h1eFJnYUxCQWt1UDJiRlJNZVhPYkVVc2hXdERnUW81QWI5aTlucjZuTWh1dnhzQVNZV1grZHBseDduSWhqSlA3QUE",
    category: "AirPods",
    name: "AirPods Pro 2 – Purple",
    desc: "Up to 2x more Active Noise Cancellation. Adaptive Audio. Hearing health features.",
    price: "₹51,900",
    sub: "MagSafe Charging Case",
  },
  {
    id: "a3",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-select-202409_FV1?wid=976&hei=916&fmt=jpeg&qlt=90&.v=WnVKRVRUTFVsYThXaWkydWViL1Q3ZDZGTE9TV3RDcGJJclBqdUtzdTJYYjNHc3NlSmU2dzJyR1kxZEwyTE1neUJkRlpCNVhYU3AwTldRQldlSnpRa0NZZXAxWFNjRXhITDI1RVE5YVpyU0E",
    category: "AirPods",
    name: "AirPods 4",
    desc: "Over-ear headphones with high-fidelity audio, ANC, and Transparency mode.",
    price: "₹12,100",
    sub: "USB-C · 5 colours",
  },
];

export const cableProducts = [
  {
    id: "c1",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MDGE4?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Cable",
    name: "Beats USB-C to USB-C Woven Cable (1.5 m) – Nitro Navy",
    desc: "Durable woven charging cable designed for fast charging, syncing, and everyday use.",
    price: "₹1,700",
    sub: "1.5 m • Nitro Navy",
  },
  {
    id: "c2",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MW2H3?wid=532&hei=582&fmt=png-alpha",
    category: "Power Adapter",
    name: "35W Dual USB-C Port Compact Power Adapter",
    desc: "Compact dual-port power adapter for efficient charging of Apple devices at home or on the go.",
    price: "₹5,399",
    sub: "35W • Dual USB-C Ports",
  },
  {
    id: "c3",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MEQ94?wid=1144&hei=1144&fmt=jpeg&qlt=90",
    category: "Cable",
    name: "Beats USB-C to USB-C Woven Short Cable (20 cm) – Bolt Black",
    desc: "Ultra-portable woven USB-C cable ideal for charging and syncing devices on the move.",
    price: "₹1,699",
    sub: "20 cm • Bolt Black",
  },
];

export const cushionProducts = [
  {
    id: "e1",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MGYT4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=bmpwMmloREYzTVZ6T25lNDBLQkVud2tuVHYzMERCZURia3c5SzJFOTlPZ1p3a1FSWkNyRzExM1dnU25TSHAxTm8zZXJNVUlPNEVxL2lGbWx2aS83Wnc",
    category: "Ear Tips",
    name: "AirPods Pro 3 Ear Tips – 2 sets (M)",
    desc: "Soft silicone ear tips designed for a secure and comfortable fit with AirPods Pro.",
    price: "₹850",
    sub: "2 sets • Medium size",
  },
  {
    id: "e2",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MWU83?wid=890&hei=890&fmt=jpeg&qlt=90&.v=dmZGa3loL0ZKUldkNHhaaTVXQUpUNHExblZJSGFXSFVPMUE2c2RxMy8rSWNvSnowcHI4U2kvUVB2WHR1bzJLTm9VVThNYjVSb21YWVVyaTBoQU5ieFE",
    category: "Ear Cushions",
    name: "AirPods Max Ear Cushions – Green",
    desc: "Breathable knit mesh cushions with memory foam for exceptional comfort and sound isolation.",
    price: "₹6,900",
    sub: "Green finish",
  },
  {
    id: "e3",
    badge: "",
    img: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MA6G4?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=MmNHRVRoZFpRMzZKT2crZEVGcWNuUWtuVHYzMERCZURia3c5SzJFOTlPaTI2T1NQUWdyeTZZTEdQZGc0bm9qVFZhNWtJYXFzVFlmeUdacWNXbVR6Rmc",
    category: "Ear Cushions",
    name: "AirPods Max Ear Cushions – Purple",
    desc: "Soft memory foam ear cushions wrapped in acoustic fabric for a premium listening experience.",
    price: "₹6,900",
    sub: "Purple finish",
  },
];
